"""Compatibility facade for database APIs.

This module remains import-compatible (`import database`, `from database import ...`)
while implementation code lives in split core modules.
"""

try:
    from . import database_core as _core
    from .database_core import (
        logger,
        MYSQL_HOST,
        MYSQL_USER,
        MYSQL_PASSWORD,
        MYSQL_DATABASE,
        MYSQL_PORT,
        USE_SQLITE_FALLBACK,
        APPROVED_ENGINEERING_DISCIPLINES,
        UNT_ALLOWED_MAJORS,
        FLAGGED_REVIEW_PATH,
        _clean_optional_text,
        _truncate_optional_text,
        _csv_optional_str,
        _parse_float,
        _parse_bool,
        _parse_int,
        _normalize_person_name,
        _sanitize_major_and_discipline,
        _append_flagged_review_urls,
        _get_or_create_normalized_entity,
        normalize_url,
        _coerce_grad_year,
        _infer_grad_year_from_school_start_date,
        _normalize_primary_education_dates,
        get_connection,
        get_direct_mysql_connection,
        init_db,
        ensure_normalized_job_title_column,
        ensure_normalized_degree_column,
        ensure_normalized_company_column,
        ensure_alumni_timestamp_columns,
        ensure_alumni_work_school_date_columns,
        ensure_alumni_major_column,
        ensure_education_columns,
        ensure_experience_analysis_columns,
        ensure_scrape_run_tracking_schema,
        ensure_all_alumni_schema_migrations,
        save_visited_profile,
        get_all_visited_profiles,
        mark_profile_needs_update,
        sync_alumni_to_visited_profiles,
        migrate_visited_history_csv_to_db,
        get_visited_profiles_stats,
        get_authorized_emails,
        is_email_authorized,
        add_authorized_email,
        remove_authorized_email,
        migrate_env_emails_to_db,
        get_user_by_email,
        create_user_with_password,
        update_user_password,
        set_must_change_password,
        update_user_role,
        get_all_users,
        delete_user,
        admin_reset_password,
        increment_scraper_activity,
        get_scraper_activity,
        create_scrape_run,
        finalize_scrape_run,
        increment_scrape_run_profiles,
        record_scrape_run_flag,
        _build_alumni_upsert_payload,
        _upsert_alumni_payload,
        upsert_scraped_profile,
        seed_alumni_data,
        has_alumni_records,
        truncate_dot_fields,
        cleanup_trailing_slashes,
        normalize_existing_grad_years,
        normalize_single_date_education_semantics,
    )
except ImportError:
    import database_core as _core
    from database_core import (
        logger,
        MYSQL_HOST,
        MYSQL_USER,
        MYSQL_PASSWORD,
        MYSQL_DATABASE,
        MYSQL_PORT,
        USE_SQLITE_FALLBACK,
        APPROVED_ENGINEERING_DISCIPLINES,
        UNT_ALLOWED_MAJORS,
        FLAGGED_REVIEW_PATH,
        _clean_optional_text,
        _truncate_optional_text,
        _csv_optional_str,
        _parse_float,
        _parse_bool,
        _parse_int,
        _normalize_person_name,
        _sanitize_major_and_discipline,
        _append_flagged_review_urls,
        _get_or_create_normalized_entity,
        normalize_url,
        _coerce_grad_year,
        _infer_grad_year_from_school_start_date,
        _normalize_primary_education_dates,
        get_connection,
        get_direct_mysql_connection,
        init_db,
        ensure_normalized_job_title_column,
        ensure_normalized_degree_column,
        ensure_normalized_company_column,
        ensure_alumni_timestamp_columns,
        ensure_alumni_work_school_date_columns,
        ensure_alumni_major_column,
        ensure_education_columns,
        ensure_experience_analysis_columns,
        ensure_scrape_run_tracking_schema,
        ensure_all_alumni_schema_migrations,
        save_visited_profile,
        get_all_visited_profiles,
        mark_profile_needs_update,
        sync_alumni_to_visited_profiles,
        migrate_visited_history_csv_to_db,
        get_visited_profiles_stats,
        get_authorized_emails,
        is_email_authorized,
        add_authorized_email,
        remove_authorized_email,
        migrate_env_emails_to_db,
        get_user_by_email,
        create_user_with_password,
        update_user_password,
        set_must_change_password,
        update_user_role,
        get_all_users,
        delete_user,
        admin_reset_password,
        increment_scraper_activity,
        get_scraper_activity,
        create_scrape_run,
        finalize_scrape_run,
        increment_scrape_run_profiles,
        record_scrape_run_flag,
        _build_alumni_upsert_payload,
        _upsert_alumni_payload,
        upsert_scraped_profile,
        seed_alumni_data,
        has_alumni_records,
        truncate_dot_fields,
        cleanup_trailing_slashes,
        normalize_existing_grad_years,
        normalize_single_date_education_semantics,
    )


__all__ = [
    "logger",
    "MYSQL_HOST",
    "MYSQL_USER",
    "MYSQL_PASSWORD",
    "MYSQL_DATABASE",
    "MYSQL_PORT",
    "USE_SQLITE_FALLBACK",
    "APPROVED_ENGINEERING_DISCIPLINES",
    "UNT_ALLOWED_MAJORS",
    "FLAGGED_REVIEW_PATH",
    "_clean_optional_text",
    "_truncate_optional_text",
    "_csv_optional_str",
    "_parse_float",
    "_parse_bool",
    "_parse_int",
    "_normalize_person_name",
    "_sanitize_major_and_discipline",
    "_append_flagged_review_urls",
    "_get_or_create_normalized_entity",
    "normalize_url",
    "_coerce_grad_year",
    "_infer_grad_year_from_school_start_date",
    "_normalize_primary_education_dates",
    "get_connection",
    "get_direct_mysql_connection",
    "init_db",
    "ensure_normalized_job_title_column",
    "ensure_normalized_degree_column",
    "ensure_normalized_company_column",
    "ensure_alumni_timestamp_columns",
    "ensure_alumni_work_school_date_columns",
    "ensure_alumni_major_column",
    "ensure_education_columns",
    "ensure_experience_analysis_columns",
    "ensure_scrape_run_tracking_schema",
    "ensure_all_alumni_schema_migrations",
    "save_visited_profile",
    "get_all_visited_profiles",
    "mark_profile_needs_update",
    "sync_alumni_to_visited_profiles",
    "migrate_visited_history_csv_to_db",
    "get_visited_profiles_stats",
    "get_authorized_emails",
    "is_email_authorized",
    "add_authorized_email",
    "remove_authorized_email",
    "migrate_env_emails_to_db",
    "get_user_by_email",
    "create_user_with_password",
    "update_user_password",
    "set_must_change_password",
    "update_user_role",
    "get_all_users",
    "delete_user",
    "admin_reset_password",
    "increment_scraper_activity",
    "get_scraper_activity",
    "create_scrape_run",
    "finalize_scrape_run",
    "increment_scrape_run_profiles",
    "record_scrape_run_flag",
    "_build_alumni_upsert_payload",
    "_upsert_alumni_payload",
    "upsert_scraped_profile",
    "seed_alumni_data",
    "has_alumni_records",
    "truncate_dot_fields",
    "cleanup_trailing_slashes",
    "normalize_existing_grad_years",
    "normalize_single_date_education_semantics",
]


def __getattr__(name):
    return getattr(_core, name)


def __dir__():
    return sorted(set(globals().keys()) | set(dir(_core)))


if __name__ == "__main__":
    import os
    import runpy

    runpy.run_path(
        os.path.join(os.path.dirname(__file__), "database_core.py"),
        run_name="__main__",
    )
