try:
    from .database_core import (
        save_visited_profile,
        get_all_visited_profiles,
        mark_profile_needs_update,
        sync_alumni_to_visited_profiles,
        migrate_visited_history_csv_to_db,
        get_visited_profiles_stats,
        get_authorized_emails,
        is_email_authorized,
        add_authorized_email,
        remove_authorized_email,
        migrate_env_emails_to_db,
        get_user_by_email,
        create_user_with_password,
        update_user_password,
        set_must_change_password,
        update_user_role,
        get_all_users,
        delete_user,
        admin_reset_password,
    )
except ImportError:
    from database_core import (
        save_visited_profile,
        get_all_visited_profiles,
        mark_profile_needs_update,
        sync_alumni_to_visited_profiles,
        migrate_visited_history_csv_to_db,
        get_visited_profiles_stats,
        get_authorized_emails,
        is_email_authorized,
        add_authorized_email,
        remove_authorized_email,
        migrate_env_emails_to_db,
        get_user_by_email,
        create_user_with_password,
        update_user_password,
        set_must_change_password,
        update_user_role,
        get_all_users,
        delete_user,
        admin_reset_password,
    )


__all__ = [
    "save_visited_profile",
    "get_all_visited_profiles",
    "mark_profile_needs_update",
    "sync_alumni_to_visited_profiles",
    "migrate_visited_history_csv_to_db",
    "get_visited_profiles_stats",
    "get_authorized_emails",
    "is_email_authorized",
    "add_authorized_email",
    "remove_authorized_email",
    "migrate_env_emails_to_db",
    "get_user_by_email",
    "create_user_with_password",
    "update_user_password",
    "set_must_change_password",
    "update_user_role",
    "get_all_users",
    "delete_user",
    "admin_reset_password",
]
